#############################################################################
# Makefile for building: QTetraMesher
# Generated by qmake (2.01a) (Qt 4.8.3) on: Sat Mar 16 23:02:26 2013
# Project:  QTetraMesher.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QTetraMesher.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -I/opt/qtetramesher/../../libQGLViewer-2.3.17 -ITetraMeshTools/include -Iinclude -ISofaTetraStuffing/include -ICGALTetrahedralize/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -L/usr/lib/i386-linux-gnu -lqglviewer-qt4 -L/opt/qtetramesher/TetraMeshTools/lib -L/opt/qtetramesher/SofaTetraStuffing/lib -L/opt/qtetramesher/../sofa/lib -L/opt/qtetramesher/../sofa/extlibs -L/opt/qtetramesher/CGALTetrahedralize/lib -lCGALTetrahedralize -lTetraMeshTools -lSofaTetraStuffing -lsofa_misc -lsofa_component_misc -lsofacore -lsofahelper -lsofadefaulttype -lsofa_mesh_collision -lsofa_deformable -lsofa_object_interaction -lsofa_base_collision -lsofa_base_mechanics -lsofa_base_topology -lsofasimulation -lGLEW -ltinyxml -lsofa_rigid -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/QGLTetraMesh.cpp \
		src/Timer.cpp \
		src/qgltetraviewer.cpp \
		src/tetrastuffingdialog.cpp \
		src/cgaltetrahedralizedialog.cpp \
		src/BaseTetraDialog.cpp moc_mainwindow.cpp \
		moc_qgltetraviewer.cpp \
		moc_tetrastuffingdialog.cpp \
		moc_cgaltetrahedralizedialog.cpp \
		moc_BaseTetraDialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		QGLTetraMesh.o \
		Timer.o \
		qgltetraviewer.o \
		tetrastuffingdialog.o \
		cgaltetrahedralizedialog.o \
		BaseTetraDialog.o \
		moc_mainwindow.o \
		moc_qgltetraviewer.o \
		moc_tetrastuffingdialog.o \
		moc_cgaltetrahedralizedialog.o \
		moc_BaseTetraDialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QTetraMesher.pro
QMAKE_TARGET  = QTetraMesher
DESTDIR       = 
TARGET        = QTetraMesher

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_tetrastuffingdialog.h ui_CGALTetrahedralizeDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QTetraMesher.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libqglviewer-qt4.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QTetraMesher.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libqglviewer-qt4.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile QTetraMesher.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QTetraMesher1.0.0 || $(MKDIR) .tmp/QTetraMesher1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QTetraMesher1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/qgltetraviewer.h src/QGLTetraMesh.h src/Timer.h src/tetrastuffingdialog.h src/cgaltetrahedralizedialog.h src/BaseTetraDialog.h .tmp/QTetraMesher1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/QGLTetraMesh.cpp src/Timer.cpp src/qgltetraviewer.cpp src/tetrastuffingdialog.cpp src/cgaltetrahedralizedialog.cpp src/BaseTetraDialog.cpp .tmp/QTetraMesher1.0.0/ && $(COPY_FILE) --parents mainwindow.ui tetrastuffingdialog.ui CGALTetrahedralizeDialog.ui mainwindow.ui .tmp/QTetraMesher1.0.0/ && (cd `dirname .tmp/QTetraMesher1.0.0` && $(TAR) QTetraMesher1.0.0.tar QTetraMesher1.0.0 && $(COMPRESS) QTetraMesher1.0.0.tar) && $(MOVE) `dirname .tmp/QTetraMesher1.0.0`/QTetraMesher1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QTetraMesher1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qgltetraviewer.cpp moc_tetrastuffingdialog.cpp moc_cgaltetrahedralizedialog.cpp moc_BaseTetraDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qgltetraviewer.cpp moc_tetrastuffingdialog.cpp moc_cgaltetrahedralizedialog.cpp moc_BaseTetraDialog.cpp
moc_mainwindow.cpp: src/cgaltetrahedralizedialog.h \
		src/tetrastuffingdialog.h \
		src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_qgltetraviewer.cpp: src/QGLTetraMesh.h \
		TetraMeshTools/include/TetraMeshTools/TetrahedronTopology.h \
		TetraMeshTools/include/TetraMeshTools/TriangleTopology.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h \
		TetraMeshTools/include/TetraMeshTools/Octree.h \
		TetraMeshTools/include/TetraMeshTools/OctreeNode.h \
		src/qgltetraviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qgltetraviewer.h -o moc_qgltetraviewer.cpp

moc_tetrastuffingdialog.cpp: src/tetrastuffingdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/tetrastuffingdialog.h -o moc_tetrastuffingdialog.cpp

moc_cgaltetrahedralizedialog.cpp: src/cgaltetrahedralizedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/cgaltetrahedralizedialog.h -o moc_cgaltetrahedralizedialog.cpp

moc_BaseTetraDialog.cpp: src/qgltetraviewer.h \
		src/QGLTetraMesh.h \
		TetraMeshTools/include/TetraMeshTools/TetrahedronTopology.h \
		TetraMeshTools/include/TetraMeshTools/TriangleTopology.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h \
		TetraMeshTools/include/TetraMeshTools/Octree.h \
		TetraMeshTools/include/TetraMeshTools/OctreeNode.h \
		src/BaseTetraDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/BaseTetraDialog.h -o moc_BaseTetraDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_tetrastuffingdialog.h ui_CGALTetrahedralizeDialog.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_tetrastuffingdialog.h ui_CGALTetrahedralizeDialog.h ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_tetrastuffingdialog.h: tetrastuffingdialog.ui
	/usr/bin/uic-qt4 tetrastuffingdialog.ui -o ui_tetrastuffingdialog.h

ui_CGALTetrahedralizeDialog.h: CGALTetrahedralizeDialog.ui
	/usr/bin/uic-qt4 CGALTetrahedralizeDialog.ui -o ui_CGALTetrahedralizeDialog.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/cgaltetrahedralizedialog.h \
		src/tetrastuffingdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/cgaltetrahedralizedialog.h \
		src/tetrastuffingdialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

QGLTetraMesh.o: src/QGLTetraMesh.cpp include/GL/glut.h \
		src/QGLTetraMesh.h \
		TetraMeshTools/include/TetraMeshTools/TetrahedronTopology.h \
		TetraMeshTools/include/TetraMeshTools/TriangleTopology.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h \
		TetraMeshTools/include/TetraMeshTools/Octree.h \
		TetraMeshTools/include/TetraMeshTools/OctreeNode.h \
		TetraMeshTools/include/TetraMeshTools/TriMeshLoader.h \
		TetraMeshTools/include/TetraMeshTools/GMSHMeshLoader.h \
		TetraMeshTools/include/TetraMeshTools/BaseMeshLoader.h \
		TetraMeshTools/include/TetraMeshTools/GMSHMeshWriter.h \
		TetraMeshTools/include/TetraMeshTools/TriMeshWriter.h \
		src/Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QGLTetraMesh.o src/QGLTetraMesh.cpp

Timer.o: src/Timer.cpp src/Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o src/Timer.cpp

qgltetraviewer.o: src/qgltetraviewer.cpp src/qgltetraviewer.h \
		src/QGLTetraMesh.h \
		TetraMeshTools/include/TetraMeshTools/TetrahedronTopology.h \
		TetraMeshTools/include/TetraMeshTools/TriangleTopology.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h \
		TetraMeshTools/include/TetraMeshTools/Octree.h \
		TetraMeshTools/include/TetraMeshTools/OctreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgltetraviewer.o src/qgltetraviewer.cpp

tetrastuffingdialog.o: src/tetrastuffingdialog.cpp src/tetrastuffingdialog.h \
		ui_tetrastuffingdialog.h \
		SofaTetraStuffing/include/SofaTetraStuffing.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tetrastuffingdialog.o src/tetrastuffingdialog.cpp

cgaltetrahedralizedialog.o: src/cgaltetrahedralizedialog.cpp src/cgaltetrahedralizedialog.h \
		ui_CGALTetrahedralizeDialog.h \
		CGALTetrahedralize/include/CGALTetrahedralize.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cgaltetrahedralizedialog.o src/cgaltetrahedralizedialog.cpp

BaseTetraDialog.o: src/BaseTetraDialog.cpp src/BaseTetraDialog.h \
		src/qgltetraviewer.h \
		src/QGLTetraMesh.h \
		TetraMeshTools/include/TetraMeshTools/TetrahedronTopology.h \
		TetraMeshTools/include/TetraMeshTools/TriangleTopology.h \
		TetraMeshTools/include/TetraMeshTools/GeometryTypes.h \
		TetraMeshTools/include/TetraMeshTools/Vec2f.h \
		TetraMeshTools/include/TetraMeshTools/Vec3f.h \
		TetraMeshTools/include/TetraMeshTools/Vec4f.h \
		TetraMeshTools/include/TetraMeshTools/TetraToolsExports.h \
		TetraMeshTools/include/TetraMeshTools/Octree.h \
		TetraMeshTools/include/TetraMeshTools/OctreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseTetraDialog.o src/BaseTetraDialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qgltetraviewer.o: moc_qgltetraviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgltetraviewer.o moc_qgltetraviewer.cpp

moc_tetrastuffingdialog.o: moc_tetrastuffingdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tetrastuffingdialog.o moc_tetrastuffingdialog.cpp

moc_cgaltetrahedralizedialog.o: moc_cgaltetrahedralizedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cgaltetrahedralizedialog.o moc_cgaltetrahedralizedialog.cpp

moc_BaseTetraDialog.o: moc_BaseTetraDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BaseTetraDialog.o moc_BaseTetraDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

